// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // strictNullChecks 下で string に絞るための非 null アサーション（挙動は従来どおり）
    url: process.env["DATABASE_URL"] as string,
  },
});
